#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if yunohost service status "$app-web" >/dev/null 2>&1; then
    yunohost service remove "$app-web"
fi

if yunohost service status "$app-sidekiq" >/dev/null 2>&1; then
    yunohost service remove "$app-sidekiq"
fi

if yunohost service status "$app-streaming" >/dev/null 2>&1; then
    yunohost service remove "$app-streaming"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd"$app-web"
ynh_config_remove_systemd"$app-sidekiq"
ynh_config_remove_systemd"$app-streaming"

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

# Remote logrotate config
ynh_config_remove_logrotate

# Remove metapackage and its dependencies
ynh_ruby_remove
ynh_nodejs_remove

# Remove swap
ynh_del_swap

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
